services:
  web:
    build: .
    ports:
      - "3000:3000"

  caddy:
    image: caddy:2.8-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    expose:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
